version: '3.3'
services:
  light-client2:
    image: lumos/ckb-light-client-dev
    build: light-client
    ports:
      - '8112:9000'
    environment:
      - ckb_host=18.162.235.225
    restart: always
    networks:
      nn1:
        ipv4_address: 192.168.4.101

  light-client3:
    image: lumos/ckb-light-client-dev
    build: light-client
    ports:
      - '8113:9000'
    environment:
      - ckb_host=18.162.235.225
    restart: always
    networks:
      nn1:
        ipv4_address: 192.168.4.102

  light-client4:
    image: lumos/ckb-light-client-dev
    build: light-client
    ports:
      - '8114:9000'
    environment:
      - ckb_host=18.162.235.225
    restart: always
    networks:
      nn1:
        ipv4_address: 192.168.4.103

  light-client5:
    image: lumos/ckb-light-client-dev
    build: light-client
    ports:
      - '8115:9000'
    environment:
      - ckb_host=18.162.235.225
    restart: always
    networks:
      nn1:
        ipv4_address: 192.168.4.105

  light-client6:
    image: lumos/ckb-light-client-dev
    build: light-client
    ports:
      - '8116:9000'
    environment:
      - ckb_host=18.162.235.225
    restart: always
    networks:
      nn1:
        ipv4_address: 192.168.4.106

  light-client:
    image: lumos/ckb-light-client-dev
    build: light-client
    ports:
      - '8111:9000'
    environment:
      - ckb_host=18.162.235.225
    restart: always
    networks:
      nn:
        ipv4_address: 192.168.3.101

networks:
  nn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.3.0/24
  nn1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.4.0/24
